# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ThreatTracker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://luloykoadksopdkas/
        username: ${{ secrets.AzureAppService_ContainerUsername_6c02f7dbe1a14458a3a08ae9d56be00e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_548f53a738ab4c26b854eea983500e4e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: luloykoadksopdkas/${{ secrets.AzureAppService_ContainerUsername_6c02f7dbe1a14458a3a08ae9d56be00e }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ThreatTracker'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_11b1e3eba41a41c4ad01a5db649a9a9c }}
        images: 'luloykoadksopdkas/${{ secrets.AzureAppService_ContainerUsername_6c02f7dbe1a14458a3a08ae9d56be00e }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}'