# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ThreatTracker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://luloykoadksopdkas/
        username: ${{ secrets.AzureAppService_ContainerUsername_150304af904c4b34a51d9c0e078be5ea }}
        password: ${{ secrets.AzureAppService_ContainerPassword_df7f1586d8304759b31ecefca5e78659 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: luloykoadksopdkas/${{ secrets.AzureAppService_ContainerUsername_150304af904c4b34a51d9c0e078be5ea }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ThreatTracker'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ccf4c23f514a4a549ed94c33b2f9388d }}
        images: 'luloykoadksopdkas/${{ secrets.AzureAppService_ContainerUsername_150304af904c4b34a51d9c0e078be5ea }}/appsvc/staticsite:${{ github.sha }}'